import {
	District,
	Hex,
	Kingdom,
	LeadershipRole,
	Settlement,
} from '../../src/api';

export const testKingdom: Kingdom = {
	id: 1,
	name: 'Untitled',
	alignment: 'Neutral',
	month: 1,
	treasury: 0,
	unrest: 0,
	holidayEdict: 'None',
	promotionEdict: 'None',
	taxationEdict: 'None',
	fame: {
		1: {
			set: false,
			value: 'none',
		},
		11: {
			set: false,
			value: 'none',
		},
		26: {
			set: false,
			value: 'none',
		},
		51: {
			set: false,
			value: 'none',
		},
		101: {
			set: false,
			value: 'none',
		},
		201: {
			set: false,
			value: 'none',
		},
	},
	government: 'Feudal Monarchy',
	options: {
		settlementModifiers: false,
		settlementGovernment: false,
		kingdomModifiers: false,
		kingdomGovernment: false,
		kingdomFame: false,
		leadershipSkills: false,
	},
};

export const testHex1: Hex = {
	id: 1,
	settlementId: 1,
	name: 'Hex Name',
	terrain: 'Plains',
	specialTerrain: [],
	explorationState: 'Settled',
	terrainImprovements: [],
	pointsOfInterest: '',
	notes: '',
};

export const testHex2: Hex = {
	id: 2,
	settlementId: 2,
	name: 'Hex Name',
	terrain: 'Plains',
	specialTerrain: [
		'Bridge',
		'Building',
		'Free City',
		'Lair',
		'Landmark',
		'Resource',
		'River',
		'Ruin',
	],
	explorationState: 'Settled',
	terrainImprovements: [
		'Aqueduct',
		'Bridge',
		'Canal',
		'Farm',
		'Fishery',
		'Fort',
		'Highway',
		'Mine',
		'Quarry',
		'Road',
		'Sawmill',
		'Vineyard',
		'Watchtower',
	],
	pointsOfInterest: 'Some string',
	notes: 'Some other string',
};

export const testSettlement1: Settlement = {
	id: 1,
	name: 'New Settlement',
	hexId: 1,
	districts: [1, 2],
	buildings: {
		Academy: 0,
		Alchemist: 0,
		Arena: 0,
		Bank: 0,
		'Bardic College': 0,
		Barracks: 0,
		'Black Market': 0,
		Brewery: 0,
		Bridge: 0,
		Bureau: 0,
		"Caster's Tower": 0,
		Castle: 0,
		Cathedral: 0,
		Cistern: 0,
		'City Wall': 0,
		'Dance Hall': 0,
		Dump: 0,
		'Everflowing Spring': 0,
		'Exotic Artisan': 0,
		'Foreign Quarter': 0,
		Foundry: 0,
		Garrison: 0,
		Granary: 0,
		Graveyard: 0,
		Guildhall: 0,
		Herbalist: 0,
		Hospital: 0,
		House: 0,
		Inn: 0,
		Jail: 0,
		Library: 0,
		'Luxury Store': 0,
		'Magic Shop': 0,
		'Magical Academy': 0,
		'Magical Streetlamps': 0,
		Mansion: 0,
		Market: 0,
		Menagerie: 0,
		'Military Academy': 0,
		Mill: 0,
		Mint: 0,
		Moat: 0,
		Monastery: 0,
		Monument: 0,
		Museum: 0,
		'Noble Villa': 0,
		Observatory: 0,
		Orphanage: 0,
		Palace: 0,
		Park: 0,
		'Paved Streets': 0,
		Pier: 0,
		'Sewer System': 0,
		Shop: 0,
		Shrine: 0,
		Smithy: 0,
		Stable: 0,
		Stockyard: 0,
		Tannery: 0,
		Tavern: 0,
		Temple: 0,
		Tenement: 0,
		Theater: 0,
		'Town Hall': 0,
		'Trade Shop': 0,
		University: 0,
		Watchtower: 0,
		Waterfront: 0,
		Waterway: 0,
	},
	wallUnrestUsed: false,
	moatUnrestUsed: false,
	government: 'Autocracy',
};

export const testSettlement2: Settlement = {
	id: 1,
	name: 'New Settlement',
	hexId: 2,
	districts: [],
	buildings: {
		Academy: 0,
		Alchemist: 0,
		Arena: 0,
		Bank: 0,
		'Bardic College': 0,
		Barracks: 0,
		'Black Market': 0,
		Brewery: 0,
		Bridge: 0,
		Bureau: 0,
		"Caster's Tower": 0,
		Castle: 0,
		Cathedral: 0,
		Cistern: 0,
		'City Wall': 0,
		'Dance Hall': 0,
		Dump: 0,
		'Everflowing Spring': 0,
		'Exotic Artisan': 0,
		'Foreign Quarter': 0,
		Foundry: 0,
		Garrison: 0,
		Granary: 0,
		Graveyard: 0,
		Guildhall: 0,
		Herbalist: 0,
		Hospital: 0,
		House: 0,
		Inn: 0,
		Jail: 0,
		Library: 0,
		'Luxury Store': 0,
		'Magic Shop': 0,
		'Magical Academy': 0,
		'Magical Streetlamps': 0,
		Mansion: 0,
		Market: 0,
		Menagerie: 0,
		'Military Academy': 0,
		Mill: 0,
		Mint: 0,
		Moat: 0,
		Monastery: 0,
		Monument: 0,
		Museum: 0,
		'Noble Villa': 0,
		Observatory: 0,
		Orphanage: 0,
		Palace: 0,
		Park: 0,
		'Paved Streets': 0,
		Pier: 0,
		'Sewer System': 0,
		Shop: 0,
		Shrine: 0,
		Smithy: 0,
		Stable: 0,
		Stockyard: 0,
		Tannery: 0,
		Tavern: 0,
		Temple: 0,
		Tenement: 0,
		Theater: 0,
		'Town Hall': 0,
		'Trade Shop': 0,
		University: 0,
		Watchtower: 0,
		Waterfront: 0,
		Waterway: 0,
	},
	wallUnrestUsed: false,
	moatUnrestUsed: false,
	government: 'Autocracy',
};

export const testDistrict1: District = {
	id: 1,
	settlementId: 1,
	name: 'New District',
	paved: false,
	sewers: false,
	north: {
		terrain: 'Land',
		wall: false,
		moat: false,
	},
	south: {
		terrain: 'Land',
		wall: false,
		moat: false,
	},
	east: {
		terrain: 'Land',
		wall: false,
		moat: false,
	},
	west: {
		terrain: 'Land',
		wall: false,
		moat: false,
	},
	lotTypeList: [null, 'Lot Type'],
};

export const testDistrict2: District = {
	id: 1,
	settlementId: 1,
	name: 'New District',
	paved: false,
	sewers: false,
	north: {
		terrain: 'Land',
		wall: false,
		moat: false,
	},
	south: {
		terrain: 'Land',
		wall: false,
		moat: false,
	},
	east: {
		terrain: 'Land',
		wall: false,
		moat: false,
	},
	west: {
		terrain: 'Land',
		wall: false,
		moat: false,
	},
	lotTypeList: [],
};

export const testRole: LeadershipRole = {
	id: 1,
	name: 'Ruler',
	heldBy: '',
	attribute: 'Charisma',
	abilityBonus: 0,
	leadership: false,
	benefit: 'Economy',
	vacant: true,
	skillBonus: 0,
};

export const testViceroy: LeadershipRole = {
	id: 1,
	name: 'Viceroy',
	heldBy: '',
	attribute: 'Intelligence/2',
	abilityBonus: 0,
	leadership: false,
	benefit: 'Economy',
	vacant: true,
	skillBonus: 0,
};
