import { BuildingListType } from './buildingListType';
import { LotType } from './lotType';

export type BuildingListTypeToLotTypeMap = Record<BuildingListType, LotType[]>;

export const buildingListTypeToLotTypeMap: BuildingListTypeToLotTypeMap = {
	'Academy H': ['Academy L', 'Academy R'],
	'Academy V': ['Academy T', 'Academy B'],
	Alchemist: ['Alchemist'],
	Bank: ['Bank'],
	Arena: ['Arena TL', 'Arena TR', 'Arena BL', 'Arena BR'],
	'Bardic College H': ['Bardic_College L', 'Bardic_College R'],
	'Bardic College V': ['Bardic_College T', 'Bardic_College B'],
	Barracks: ['Barracks'],
	'Black Market': ['Black_Market'],
	Brewery: ['Brewery'],
	'Bridge 1 H': ['Bridge_1_H'],
	'Bridge 1 V': ['Bridge_1_V'],
	'Bridge 2 L': ['Bridge_2_L'],
	'Bridge 2 R': ['Bridge_2_R'],
	'Bridge 2 T': ['Bridge_2_T'],
	'Bridge 2 B': ['Bridge_2_B'],
	'Bridge 3 H': ['Bridge_3_H'],
	'Bridge 3 V': ['Bridge_3_V'],
	'Bureau H': ['Bureau L', 'Bureau R'],
	'Bureau V': ['Bureau T', 'Bureau B'],
	"Caster's Tower": ["Caster's_Tower"],
	Castle: ['Castle TL', 'Castle TR', 'Castle BL', 'Castle BR'],
	Cathedral: ['Cathedral TL', 'Cathedral TR', 'Cathedral BL', 'Cathedral BR'],
	Cistern: ['Cistern'],
	'Dance Hall': ['Dance Hall'],
	Dump: ['Dump'],
	'Exotic Artisan': ['Exotic_Artisan'],
	'Foreign Quarter': [
		'Foreign_Quarter TL',
		'Foreign_Quarter TR',
		'Foreign_Quarter BL',
		'Foreign_Quarter BR',
	],
	'Foundry H': ['Foundry L', 'Foundry R'],
	'Foundry V': ['Foundry T', 'Foundry B'],
	'Garrison H': ['Garrison L', 'Garrison R'],
	'Garrison V': ['Garrison T', 'Garrison B'],
	Granary: ['Granary'],
	Graveyard: ['Graveyard'],
	'Guildhall H': ['Guildhall L', 'Guildhall R'],
	'Guildhall V': ['Guildhall T', 'Guildhall B'],
	Herbalist: ['Herbalist'],
	'Hospital H': ['Hospital L', 'Hospital R'],
	'Hospital V': ['Hospital T', 'Hospital B'],
	House: ['House'],
	Inn: ['Inn'],
	Jail: ['Jail'],
	Library: ['Library'],
	'Luxury Store': ['Luxury_Store'],
	'Magic Shop': ['Magic_Shop'],
	'Magical Academy H': ['Magical_Academy L', 'Magical_Academy R'],
	'Magical Academy V': ['Magical_Academy T', 'Magical_Academy B'],
	Mansion: ['Mansion'],
	'Market H': ['Market L', 'Market R'],
	'Market V': ['Market T', 'Market B'],
	Menagerie: ['Menagerie TL', 'Menagerie TR', 'Menagerie BL', 'Menagerie BR'],
	'Military Academy H': ['Military_Academy L', 'Military_Academy R'],
	'Military Academy V': ['Military_Academy T', 'Military_Academy B'],
	Mill: ['Mill'],
	Mint: ['Mint'],
	'Monastery H': ['Monastery L', 'Monastery R'],
	'Monastery V': ['Monastery T', 'Monastery B'],
	Monument: ['Monument'],
	'Museum H': ['Museum L', 'Museum R'],
	'Museum V': ['Museum T', 'Museum B'],
	'Noble Villa H': ['Noble_Villa L', 'Noble_Villa R'],
	'Noble Villa V': ['Noble_Villa T', 'Noble_Villa B'],
	Observatory: ['Observatory'],
	Orphanage: ['Orphanage'],
	Palace: ['Palace TL', 'Palace TR', 'Palace BL', 'Palace BR'],
	Park: ['Park'],
	Pier: ['Pier'],
	Shop: ['Shop'],
	Shrine: ['Shrine'],
	Smithy: ['Smithy'],
	Stable: ['Stable'],
	Stockyard: ['Stockyard TL', 'Stockyard TR', 'Stockyard BL', 'Stockyard BR'],
	Tannery: ['Tannery'],
	Tavern: ['Tavern'],
	'Temple H': ['Temple L', 'Temple R'],
	'Temple V': ['Temple T', 'Temple B'],
	Tenement: ['Tenement'],
	'Theater H': ['Theater L', 'Theater R'],
	'Theater V': ['Theater T', 'Theater B'],
	'Town Hall H': ['Town_Hall L', 'Town_Hall R'],
	'Town Hall V': ['Town_Hall T', 'Town_Hall B'],
	'Trade Shop': ['Trade_Shop'],
	University: [
		'University TL',
		'University TR',
		'University BL',
		'University BR',
	],
	Watchtower: ['Watchtower'],
	'Waterfront Bottom': [
		'Waterfront_Bottom TL',
		'Waterfront_Bottom TR',
		'Waterfront_Bottom BL',
		'Waterfront_Bottom BR',
	],
	'Waterfront TL Corner': [
		'Waterfront_TL_Corner TL',
		'Waterfront_TL_Corner TR',
		'Waterfront_TL_Corner BL',
		'Waterfront_TL_Corner BR',
	],
	'Waterfront TR Corner': [
		'Waterfront_TR_Corner TL',
		'Waterfront_TR_Corner TR',
		'Waterfront_TR_Corner BL',
		'Waterfront_TR_Corner BR',
	],
	'Waterfront BL Corner': [
		'Waterfront_BL_Corner TL',
		'Waterfront_BL_Corner TR',
		'Waterfront_BL_Corner BL',
		'Waterfront_BL_Corner BR',
	],
	'Waterfront BR Corner': [
		'Waterfront_BR_Corner TL',
		'Waterfront_BR_Corner TR',
		'Waterfront_BR_Corner BL',
		'Waterfront_BR_Corner BR',
	],
	'Waterfront Left': [
		'Waterfront_Left TL',
		'Waterfront_Left TR',
		'Waterfront_Left BL',
		'Waterfront_Left BR',
	],
	'Waterfront Right': [
		'Waterfront_Right TL',
		'Waterfront_Right TR',
		'Waterfront_Right BL',
		'Waterfront_Right BR',
	],
	'Waterfront Top': [
		'Waterfront_Top TL',
		'Waterfront_Top TR',
		'Waterfront_Top BL',
		'Waterfront_Top BR',
	],
	'Waterway H': ['Waterway_H'],
	'Waterway V': ['Waterway_V'],
	'Waterway TL': ['Waterway_TL_Corner'],
	'Waterway TR': ['Waterway_TR_Corner'],
	'Waterway BL': ['Waterway_BL_Corner'],
	'Waterway BR': ['Waterway_BR_Corner'],
	'Waterway Cross': ['Waterway_Cross'],
	'Waterway Lake H': ['Waterway_Lake_H'],
	'Waterway Lake V': ['Waterway_Lake_V'],
	'Waterway Lake L': ['Waterway_Lake_L'],
	'Waterway Lake R': ['Waterway_Lake_R'],
	'Waterway Lake T': ['Waterway_Lake_T'],
	'Waterway Lake B': ['Waterway_Lake_B'],
	'Waterway Lake TL': ['Waterway_Lake_TL_Corner'],
	'Waterway Lake TR': ['Waterway_Lake_TR_Corner'],
	'Waterway Lake BL': ['Waterway_Lake_BL_Corner'],
	'Waterway Lake BR': ['Waterway_Lake_BR_Corner'],
	'Waterway Long H': ['Waterway_Long_H L', 'Waterway_Long_H R'],
	'Waterway Long V': ['Waterway_Long_V T', 'Waterway_Long_V B'],
	'Waterway Long L': ['Waterway_Long_L L', 'Waterway_Long_L R'],
	'Waterway Long R': ['Waterway_Long_R L', 'Waterway_Long_R R'],
	'Waterway Long T': ['Waterway_Long_T T', 'Waterway_Long_T B'],
	'Waterway Long B': ['Waterway_Long_B T', 'Waterway_Long_B B'],
	'Waterway Long TL Corner H': [
		'Waterway_Long_TL_Corner L',
		'Waterway_Long_TL_Corner R',
	],
	'Waterway Long TL Corner V': [
		'Waterway_Long_TL_Corner T',
		'Waterway_Long_TL_Corner B',
	],
	'Waterway Long TR Corner H': [
		'Waterway_Long_TR_Corner L',
		'Waterway_Long_TR_Corner R',
	],
	'Waterway Long TR Corner V': [
		'Waterway_Long_TR_Corner T',
		'Waterway_Long_TR_Corner B',
	],
	'Waterway Long BL Corner H': [
		'Waterway_Long_BL_Corner L',
		'Waterway_Long_BL_Corner R',
	],
	'Waterway Long BL Corner V': [
		'Waterway_Long_BL_Corner T',
		'Waterway_Long_BL_Corner B',
	],
	'Waterway Long BR Corner H': [
		'Waterway_Long_BR_Corner L',
		'Waterway_Long_BR_Corner R',
	],
	'Waterway Long BR Corner V': [
		'Waterway_Long_BR_Corner T',
		'Waterway_Long_BR_Corner B',
	],
};
