export type LotType =
	| 'Academy L'
	| 'Academy R'
	| 'Academy T'
	| 'Academy B'
	| 'Alchemist'
	| 'Arena TL'
	| 'Arena TR'
	| 'Arena BL'
	| 'Arena BR'
	| 'Bank'
	| 'Bardic_College L'
	| 'Bardic_College R'
	| 'Bardic_College T'
	| 'Bardic_College B'
	| 'Barracks'
	| 'Black_Market'
	| 'Brewery'
	| 'Bridge'
	| 'Bureau L'
	| 'Bureau R'
	| 'Bureau T'
	| 'Bureau B'
	| "Caster's_Tower"
	| 'Castle TL'
	| 'Castle TR'
	| 'Castle BL'
	| 'Castle BR'
	| 'Cathedral TL'
	| 'Cathedral TR'
	| 'Cathedral BL'
	| 'Cathedral BR'
	| 'Cistern'
	| 'Dance Hall'
	| 'Dump'
	// 'Everflowing Spring' |
	| 'Exotic_Artisan'
	| 'Foreign_Quarter TL'
	| 'Foreign_Quarter TR'
	| 'Foreign_Quarter BL'
	| 'Foreign_Quarter BR'
	| 'Foundry L'
	| 'Foundry R'
	| 'Foundry T'
	| 'Foundry B'
	| 'Garrison L'
	| 'Garrison R'
	| 'Garrison T'
	| 'Garrison B'
	| 'Granary'
	| 'Graveyard'
	| 'Guildhall L'
	| 'Guildhall R'
	| 'Guildhall T'
	| 'Guildhall B'
	| 'Herbalist'
	| 'Hospital L'
	| 'Hospital R'
	| 'Hospital T'
	| 'Hospital B'
	| 'House'
	| 'Inn'
	| 'Jail'
	| 'Library'
	| 'Luxury_Store'
	| 'Magic_Shop'
	| 'Magical_Academy L'
	| 'Magical_Academy R'
	| 'Magical_Academy T'
	| 'Magical_Academy B'
	// 'Magical Streetlamps' |
	| 'Mansion'
	| 'Market L'
	| 'Market R'
	| 'Market T'
	| 'Market B'
	| 'Menagerie TL'
	| 'Menagerie TR'
	| 'Menagerie BL'
	| 'Menagerie BR'
	| 'Military_Academy L'
	| 'Military_Academy R'
	| 'Military_Academy T'
	| 'Military_Academy B'
	| 'Mill'
	| 'Mint'
	| 'Monastery L'
	| 'Monastery R'
	| 'Monastery T'
	| 'Monastery B'
	| 'Monument'
	| 'Museum L'
	| 'Museum R'
	| 'Museum T'
	| 'Museum B'
	| 'Noble_Villa L'
	| 'Noble_Villa R'
	| 'Noble_Villa T'
	| 'Noble_Villa B'
	| 'Observatory'
	| 'Orphanage'
	| 'Palace TL'
	| 'Palace TR'
	| 'Palace BL'
	| 'Palace BR'
	| 'Park'
	| 'Pier'
	| 'Shop'
	| 'Shrine'
	| 'Smithy'
	| 'Stable'
	| 'Stockyard TL'
	| 'Stockyard TR'
	| 'Stockyard BL'
	| 'Stockyard BR'
	| 'Tannery'
	| 'Tavern'
	| 'Temple L'
	| 'Temple R'
	| 'Temple T'
	| 'Temple B'
	| 'Tenement'
	| 'Theater L'
	| 'Theater R'
	| 'Theater T'
	| 'Theater B'
	| 'Town_Hall L'
	| 'Town_Hall R'
	| 'Town_Hall T'
	| 'Town_Hall B'
	| 'Trade_Shop'
	| 'University TL'
	| 'University TR'
	| 'University BL'
	| 'University BR'
	| 'Watchtower'
	| 'Waterfront TL'
	| 'Waterfront TR'
	| 'Waterfront BL'
	| 'Waterfront BR'
	| 'Waterway';
